### ISSUE TITLE
Crash in Multiplayer when Non-Admin person attempts to open Teleporter Menu

### ISSUE THREAD

**Issue by iancj97** [WhatheWorld/PersonalTeleporter#20]
I host a server, with one other person in it. I can expand and collapse the Teleport menu, but when the other person does, Factorio crashes. This occurs regardless of whether the person in question has a personal teleporter in their inventory.

At no point does this issue reproduce with me, the server host.

![Capture](https://user-images.githubusercontent.com/25238195/78812017-c1b3d700-7998-11ea-9fb0-ad1cd8f32d90.PNG)

**Comment by WhatheWorld** [comment]
should be fixed in V0.3.11.
